### ISSUE TITLE
Upgrade to Presto 0.186 breaks the docker image

### ISSUE THREAD

**Issue by senior** [wwwiiilll/presto-mb-ci#2]
The offending line might be [here](https://github.com/wwwiiilll/presto-mb-ci/commit/efd416ba2b1d111c28d3e50e80aa630f36141613#diff-3254677a7917c6c01f55212f86c57fbfR1) but the docker container will no longer start with the most recent image. The issue appears to be that the image no longer has Python on the path and the Presto launcher requires it. I've been able to reproduce the problem locally and the previous image does include python on the PATH.

**Comment by willtrnr** [comment]
Oh snap, didn't catch that, I usually test another internal similar image before. But I see you guys forked it, so it's better that way anyway in case I can't be reached.

**Comment by willtrnr** [comment]
FWIW I pushed a fixed version, I'll consider this closed, but I probably won't be touching it anymore since you now have your fork.
